"""Detect a sequence-number affix on a name (folder / file stem / tag value) and strip it.

A leading '02 - Yendi' or trailing 'Yendi (2)' carries a series sequence number stuck to a
title. This is the ONE place that decides whether such a number is present, what the clean
title is, and how confident we are. Reused by the numbered-siblings classifier axiom, the
lone-title cleaner in IDENTIFY, and filename_cluster — so number-stripping has one behavior
and one whitespace guard. Pure: no I/O.

Confidence:
- "strong": the number is bracket-delimited ('1) …', '… (2)', '… [3]') OR there is whitespace
  on at least one side of the separator ('02 - Yendi'). Safe to strip even for a lone book.
- "weak": a separator with no surrounding whitespace ('30-Day', 'Catch-22') — reads as a
  compound; only trust it with corroboration (a sibling ramp or a series tag).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Literal

# Separators a leading number may hang off: dash, underscore, close-paren/bracket, dot, en/em dash.
_LEAD_SEPS = r"-_)\].–—"  # noqa: RUF001
# Trailing separators (bare, non-bracket): dash / underscore / en / em dash. Brackets handled apart.
_TRAIL_SEPS = r"-_–—"  # noqa: RUF001
_NUM = r"\d{1,3}(?:\.\d{1,2})?"          # 1-3 integer digits (4-digit years excluded), optional decimal

_LEADING = re.compile(rf"^\s*(?P<num>{_NUM})(?P<lsp>\s*)(?P<sep>[{_LEAD_SEPS}])(?P<rsp>\s*)(?P<rest>\S.*)$")
_TRAIL_BRACKET = re.compile(rf"^(?P<rest>.*?\S)\s*[(\[]\s*(?P<num>{_NUM})\s*[)\]]\s*$")
_TRAIL_SEP = re.compile(rf"^(?P<rest>.*?\S)(?P<lsp>\s*)[{_TRAIL_SEPS}](?P<rsp>\s*)(?P<num>{_NUM})\s*$")
_HAS_LETTER = re.compile(r"[^\W\d_]", re.UNICODE)


@dataclass(frozen=True)
class SequenceAffix:
    sequence: float
    cleaned: str
    confidence: Literal["strong", "weak"]


def _build(num: str, rest: str, *, strong: bool) -> SequenceAffix | None:
    rest = rest.strip()
    if not _HAS_LETTER.search(rest):     # the remainder must be a real title, not more digits
        return None
    return SequenceAffix(sequence=float(num), cleaned=rest, confidence="strong" if strong else "weak")


def parse_sequence_affix(name: str) -> SequenceAffix | None:
    """Return the sequence + cleaned title + confidence for a name with a numeric affix, else None."""
    if not name:
        return None
    m = _LEADING.match(name)
    if m:
        strong = m.group("sep") in ")]" or bool(m.group("lsp") or m.group("rsp"))
        return _build(m.group("num"), m.group("rest"), strong=strong)
    m = _TRAIL_BRACKET.match(name)
    if m:
        return _build(m.group("num"), m.group("rest"), strong=True)   # bracketed is always strong
    m = _TRAIL_SEP.match(name)
    if m:
        return _build(m.group("num"), m.group("rest"), strong=bool(m.group("lsp") or m.group("rsp")))
    return None


# A series-code affix used as a title prefix: "SB 01 - StarBridge", "DC 02 - Tears of War",
# "Bk 15 - ...", "Book 18 - ...". A 1-5 letter code (or the word Book/Bk) + a 1-3 digit number +
# a separator. Comparison-only: this lines residual titles up, it never rewrites a stored title.
_SERIES_CODE_AFFIX = re.compile(
    r"^\s*(?:book|bk|[A-Za-z]{1,5})\s*\d{1,3}\s*[-:.]\s*", re.IGNORECASE
)


def strip_series_code_affix(title: str) -> str:
    """Strip a leading series-code affix ('SB 01 - StarBridge' -> 'StarBridge'). Returns the input
    unchanged when there is no such affix, or when stripping would leave no letters. Over-stripping is
    safe for its sole caller (residual comparison): a shorter tag residual can only make two titles
    agree or abstain, never falsely contradict."""
    if not title:
        return title
    m = _SERIES_CODE_AFFIX.match(title)
    if not m:
        return title
    rest = title[m.end():].strip()
    return rest if _HAS_LETTER.search(rest) else title


# A trailing series-book affix: "Some Title - Bk01", "Some Title - Book 1", "Silent Songs: Book 12".
# The explicit Book/Bk word makes it a book-number tail (not a title that merely ends in a number
# like "Fahrenheit 451"), so this is conservative to strip from an autogenerated title.
_SERIES_BOOK_SUFFIX = re.compile(r"\s*[-–—:]\s*(?:book|bk)\s*\d{1,3}\s*$", re.IGNORECASE)  # noqa: RUF001


def strip_series_book_suffix(title: str) -> str:
    """Strip a trailing series-book affix ('Some Title - Bk01' -> 'Some Title'). Returns the input
    unchanged when there is no such affix or stripping would leave no letters."""
    if not title:
        return title
    stripped = _SERIES_BOOK_SUFFIX.sub("", title).strip()
    return stripped if stripped != title and _HAS_LETTER.search(stripped) else title


# A ripped-encoding artifact: a token carrying an '@' bitrate/samplerate marker ("16@64.44m",
# "@40k-44m"), optionally led by an abridged/unabridged marker or a part number ("UA 16@64.44m",
# "Unabr @40k-44m", "U @64"). Real-data check: '@' appears in 55 titles, 0 authors, and every
# occurrence is an encoding artifact — none legitimate — so it is safe to strip outright.
_ENCODING_ARTIFACT = re.compile(
    r"\s*[(\[]?\s*(?:unabridged|unabr|una|ua|u)?\s*\d*\s*@\s*[\w.\-]+\s*[)\]]?", re.IGNORECASE)


def strip_encoding_artifact(title: str) -> str:
    """Strip a ripped-encoding '@' artifact ('Fevre Dream (Unabr @40k-44m)' -> 'Fevre Dream',
    'Sliding Scales UA 16@64.44m' -> 'Sliding Scales'). Returns the input unchanged when there is no
    '@' or stripping would leave no letters."""
    if not title or "@" not in title:
        return title
    stripped = " ".join(_ENCODING_ARTIFACT.sub(" ", title).split()).strip(" -–—:.")  # noqa: RUF001
    return stripped if _HAS_LETTER.search(stripped) else title


# --- Whole-title cleaning: strip the sequence/underscore/junk a filename leaves in the title, WITHOUT
# touching a legitimate number (a bare unpadded trailing number is part of the title — 'Slaughterhouse
# 5', 'Catch 22', 'Fahrenheit 451'). Surgical by design; validated 0 legit broken / 350 cleaned on the
# real library. See the identity-first grouping thread.
_CT_INT = r"\d{1,3}(?!\d)"                       # 1-3 digits, never a 4-digit year
_CT_PAD = r"0\d{1,2}(?!\d)"                       # a zero-padded index (01, 001) — an index, not a title number
_CT_MARK = r"(?:unb|una|ua|cd|disc|disk|pt|part|track|section)"
# a parenthetical abridged/unabridged label — junk, remove whole
_CT_PAREN = re.compile(r"\s*[(\[]\s*(?:un)?abr?(?:idged)?\s*[)\]]", re.IGNORECASE)
# a mixed alpha+digit token >= 8 chars — an encoding hash ('A1I69YWSTVC2NT', 'mp332...')
_CT_HASH = re.compile(r"\b(?=[A-Za-z0-9]*[A-Za-z])(?=[A-Za-z0-9]*\d)[A-Za-z]*\d[A-Za-z0-9]{6,}\b")
_CT_JUNK = re.compile(
    r"\b(output|mp3|m4b|vbr|cbr|kbps|khz|joined|encoded|converted|ecd)\b", re.IGNORECASE)
# a trailing part-sequence: dash/marker-attached number, a compound N-N, or a zero-padded bare number —
# NOT a bare unpadded trailing number (a real title ending in a number).
_CT_TRAIL = re.compile(
    rf"(?:\s*[-–]\s*(?:{_CT_MARK}[\s-]*)?{_CT_INT}(?:-{_CT_INT})?"  # noqa: RUF001
    rf"|\s+{_CT_MARK}[\s-]*{_CT_INT}|\s+{_CT_PAD}|\s+{_CT_INT}-{_CT_INT})\s*$", re.IGNORECASE)
# a leading part-index: 'N of M', a zero-padded index, or a two-number 'NN MM' run (never a 4-digit year)
_CT_LEAD = re.compile(
    rf"^\s*(?:{_CT_INT}\s+of\s+{_CT_INT}|{_CT_PAD}(?:[\s._-]+{_CT_INT})?"
    rf"|{_CT_INT}[\s._-]+{_CT_INT})[\s._-]+(?=\S)", re.IGNORECASE)


def clean_title(title: str) -> str:
    """Strip the filename cruft a title carries — encoding artifacts, underscores, glued PascalCase,
    leading/trailing part-sequences, abridged labels — while preserving a legitimate title (a bare
    unpadded trailing number, a real name). Returns the input unchanged when cleaning would leave no
    letters (an all-junk title is left for MATCH/flagging, not blanked)."""
    if not title:
        return title
    from colophon.core.normalize import _split_pascal
    s = strip_encoding_artifact(title)
    s = _CT_PAREN.sub("", s)
    s = s.replace("_", " ")
    s = _CT_HASH.sub(" ", s)
    s = _CT_JUNK.sub(" ", s)
    s = _CT_LEAD.sub("", s)
    s = _CT_TRAIL.sub("", s)
    s = strip_series_book_suffix(strip_series_code_affix(s))
    # Split PascalCase LAST, so a title left glued by the affix strip ('SB 01 - StarBridge' ->
    # 'StarBridge') is split in the same pass — keeps clean_title idempotent.
    if " " not in s.strip():
        s = _split_pascal(s)
    s = " ".join(s.split()).strip(" -–—:._")      # noqa: RUF001
    return s if s and _HAS_LETTER.search(s) else title
